# Pertemuan 3

## List

In [22]:
aList = ["Rara", 19, "Tokyo", True]

In [23]:
aList

['Rara', 19, 'Tokyo', True]

In [24]:
type(aList)

list

In [25]:
bin_flowers = ['Mawar','Matahari','Tulip','Anggrek']

## Tuples

In [26]:
bin_flowers = ('Mawar','Matahari','Tulip','Anggrek')
print(f"Elemen kedua dari tuples adalah {bin_flowers[1]}")

Elemen kedua dari tuples adalah Matahari


In [27]:
print(f"Elemen ketiga sampai terakhir adalah {bin_flowers[2:]}")

Elemen ketiga sampai terakhir adalah ('Tulip', 'Anggrek')


In [30]:
nested_tuple = (1,2,(100,1000,10000),5)
print(f"Value maksimal dari inner tuple {max(nested_tuple[2])}")

Value maksimal dari inner tuple 10000


## Dictionary

In [31]:
bin_food = {
    "manual_food" : "Ketoprak",
    "approved_food" : "Soto mie",
    "refused_food" : "Kerak telor"
}

In [32]:
print(bin_food)

{'manual_food': 'Ketoprak', 'approved_food': 'Soto mie', 'refused_food': 'Kerak telor'}


In [33]:
bin_food.get('approved_food')

'Soto mie'

In [34]:
bin_food['approved_food']

'Soto mie'

In [35]:
bin_food['approved'] = "Mie ayam"
print(bin_food)

{'manual_food': 'Ketoprak', 'approved_food': 'Soto mie', 'refused_food': 'Kerak telor', 'approved': 'Mie ayam'}


## Sets

In [37]:
blue = {'Langit','Laut'}
print(blue)

{'Langit', 'Laut'}


In [40]:
kegiatan = {'Membaca','Nugas','Jalan-jalan sore'}
hobi = {'Membaca','Bernyanyi','Menari','Jalan-jalan sore'}

In [41]:
print(f"Gabungan dari sets kegiatan dan hobi yaitu {kegiatan|hobi}")

Gabungan dari sets kegiatan dan hobi yaitu {'Nugas', 'Bernyanyi', 'Membaca', 'Jalan-jalan sore', 'Menari'}


In [43]:
print(f"Hal yang sama dalam kegiatan dan hobi yaitu {kegiatan&hobi}")

Hal yang sama dalam kegiatan dan hobi yaitu {'Membaca', 'Jalan-jalan sore'}


## Data Frame

In [51]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Harsley' , 19, True],
    ['2', 'Putra', 13, False],
    ['3', 'Joy'  , 22, True]])
df.columns = ['No', 'Nama', 'Umur', 'Ket.']
print(df)

  No     Nama  Umur   Ket.
0  1  Harsley    19   True
1  2    Putra    13  False
2  3      Joy    22   True


In [53]:
df[['Nama', 'Umur']]

Nama  Umur
0  Harsley    19
1    Putra    13
2      Joy    22

In [54]:
df.iloc[:,3]

0     True
1    False
2     True
Name: Ket., dtype: bool

In [55]:
df.iloc[1:3,:]

No   Nama  Umur   Ket.
1  2  Putra    13  False
2  3    Joy    22   True

In [56]:
df.iloc[0:2,:]

No     Nama  Umur   Ket.
0  1  Harsley    19   True
1  2    Putra    13  False

In [61]:
df[df.Umur>20]

No Nama  Umur  Ket.
2  3  Joy    22  True

## Matriks

In [67]:
import numpy as np
myMatrix = np.array([[5,6,7],[15,16,17],[31,32,33]])

In [68]:
print(myMatrix)

[[ 5  6  7]
 [15 16 17]
 [31 32 33]]


In [69]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [70]:
myMatrix.transpose()

array([[ 5, 15, 31],
       [ 6, 16, 32],
       [ 7, 17, 33]])

## Vector

In [72]:
myVector = [5,7,16,20]
print(myVector)

[5, 7, 16, 20]


In [73]:
print(type(myVector))

<class 'list'>


In [74]:
myVector = np.array([5,7,16,20])
print(myVector)

[ 5  7 16 20]


In [75]:
print(type(myVector))

<class 'numpy.ndarray'>


## Stack

In [76]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self,item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)
        

In [77]:
stack = Stack()
stack.push('Ungu')
stack.push('Biru')
stack.push('Kuning')
stack.push('Merah jambu')

In [78]:
stack.pop()

'Merah jambu'

In [80]:
stack.isEmpty()

False

In [81]:
colors = ['Ungu']

In [82]:
colors.append('Biru')
colors.append('Kuning')
colors.append('Merah jambu')

In [83]:
colors

['Ungu', 'Biru', 'Kuning', 'Merah jambu']

## Queue

In [84]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self,item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)
        

In [85]:
queue = Queue()

In [86]:
queue.enqueue('Ungu')

In [87]:
queue.enqueue('Biru')

In [88]:
queue.enqueue('Kuning')

In [89]:
queue.enqueue('Merah jambu')

In [90]:
print(f"Size queue adalah {queue.size()}")

Size queue adalah 4


In [91]:
print(queue.dequeue())

Ungu
